### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by knchst** [EndouMari/TabPageViewController#14]
IQONのアプリの様にUITabBarControllerでこちらのライブラリを扱う際の実装方法を教えて欲しいです。

**Comment by EndouMari** [comment]
サンプルコードをつくったのでこちらを参考にしてみてください。
https://github.com/EndouMari/SampleTab

**Comment by knchst** [comment]
ありがとうございました！すごく参考になりました！！
今後もこちらのライブラリを愛用させていただきます✋😎
