### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [EndouMari/TabPageViewController#29]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by aadilimperoit** [comment]
Any update here ? +1

**Comment by leosimas** [comment]
Just found this project but I can't use it right now :(

**Comment by rinkon** [comment]
Code from the branch Swift 3.0 doesn't show the bar under the highlighted page title.

**Comment by EndouMari** [comment]
Thanks!
fixed id.

https://github.com/EndouMari/TabPageViewController/pull/32

**Comment by lfarah** [comment]
Hey @EndouMari, thanks! You're awesome 👍 😃
