### ISSUE TITLE
Content Size

### ISSUE THREAD

**Issue by NhutHuynhiOSDev-hub** [EndouMari/TabPageViewController#31]
Hi! 
This is cold!! but how can I set autoLayout or just simple the size of the content ?

thanks! 👍

**Comment by EndouMari** [comment]
tab view height?

**Comment by NhutHuynhiOSDev-hub** [comment]
just the width of the Content, I make the tabPageViewController as a subclass of the UIView(gray color)
and my small problem here: 
![screen shot 2016-10-26 at 5 00 57 pm](https://cloud.githubusercontent.com/assets/22335175/19721784/fa8bc9c0-9b9d-11e6-8c15-f5b3a9a7ec6b.png)

**Comment by EndouMari** [comment]
Sorry, I don't understand.
can you tell me more.

**Comment by NhutHuynhiOSDev-hub** [comment]
I see you build a function "private func configuredTabView() -> TabView " is that set the Size for the tabPageViewController right ?

I just try to but the tabPageViewController into a UIView  as the subView any I don't known why it don't fill the UIView (the view with gray color)
Sorry for my english is little ^_^

**Comment by EndouMari** [comment]
please show me view debugger >_<
