### ISSUE TITLE
keep scrolling without releasing your finger, the title of the tab changes.

### ISSUE THREAD

**Issue by GreenSpo** [EndouMari/TabPageViewController#34]
When I keep scrolling without releasing your finger, the title of the tab changes.

I attach a gif file to a movie.

![movie](https://cloud.githubusercontent.com/assets/24241565/20699357/42b431bc-b64a-11e6-9617-4f059177f047.gif)

Is there a solution to this problem?

**Comment by EndouMari** [comment]
Sorry, it's bug.

TabPageViewController is using UIPageViewControllerDelegate.
UIPageViewControllerDelegate can not detect scrolling behavior without releasing your finger.

Do you have good idea?
