### ISSUE TITLE
Carthage error : Module file's minimum deployment target is ios8.3?

### ISSUE THREAD

**Issue by litt1e-p** [EndouMari/TabPageViewController#4]
I am using carthage for TabPageViewController, there is an import error message show: Module file's minimum deployment target is ios8.3?
is it the minimum version? My environment: Xcode7.3 swift2.2 deployment target: iOS8.0

**Comment by EndouMari** [comment]
Changed deployment target 8.0.
Thanks!

**Comment by litt1e-p** [comment]
thanks

2016年4月16日星期六，EndouMari notifications@github.com 写道：
