### ISSUE TITLE
Hide TabBar

### ISSUE THREAD

**Issue by ducnv55** [EndouMari/TabPageViewController#52]
Can you show me how can I hide **TabBar** (the horizontal scroll view)
I want to hide it when pull down the **tableview** (to make more space for tableview's content)
Please help me.
Thank you.

**Comment by EndouMari** [comment]
Thanks issue!

We will add that feature and update, please wait.

**Comment by EndouMari** [comment]
Fixed version(0.2.6) has just released. Please use the latest one.

Example code
https://github.com/EndouMari/TabPageViewController/blob/master/Demo/TabPageViewControllerDemo/ListViewController.swift

![3 -30-2017 22-24-11](https://cloud.githubusercontent.com/assets/8034270/24507825/85bd9500-159c-11e7-945b-94b96178c4cf.gif)

**Comment by ducnv55** [comment]
Thank you so muchhhhh :+1:

**Comment by ducnv55** [comment]
Sorry for late response.
I just used your lib, everything works fine. Thank you for this feature.
But can you make more options to hide **ONLY** **Scroll page View** (not include navigation bar)

I can add code to show navigation bar, but app show a Black space when navigation bar animated.

One more thing, can you fix your lib to hide **Scroll page view** when dragging, even when drag slowly?
Currently, your lib only hide **Scroll page view** when release dragging & drag fast, not **while dragging**

Very appreciate if you have this feature.

**Comment by ducnv55** [comment]
I forked your lib and fix above issue.
I add another **option** in **TabPageOption**, named "hidesNavigationBarOnSwipe"
When **hidesNavigationBarOnSwipe == true**, navigation bar will be hidden.
When **hidesNavigationBarOnSwipe == false**, navigation bar will be shown.

Please accept my commit and merge it into master. Thank you so much.
