### ISSUE TITLE
When isInfinty is true, cannot select tabs more than once

### ISSUE THREAD

**Issue by isseium** [EndouMari/TabPageViewController#57]
## Sorry for writing in Japanese.

いつも使わさせていただいております。日本語で失礼します。

この度、動作環境を xcode 8.3, swift 3.1 にして 0.2.6 にバージョンアップしたところ、 isInfinity が true だと 2回目か3回目くらいにタブが選択できなくなりました。

以下が動作キャプチャです。

https://i.gyazo.com/190a4f02265d4795e8ff7038ea7cf4f5.mp4

ソースコードを拝見しつつデバッグしたところ

https://github.com/EndouMari/TabPageViewController/blob/master/Sources/TabView.swift#L258

上記のif文をなくすと見た目上は正常に動作するようになりました。

https://i.gyazo.com/107a8fdd661b02a414076e3a58350607.mp4

深いところまでは追っていないのでこのif文を消すだけで問題がないか確認いただけますでしょうか。
このあとPRをお送りします。よろしくお願いします。

==
Automatic translation using Google translation

I have upgraded the operating environment to xcode 8.3, swift 3.1 and upgraded it to 0.2.6, and when isInfinity is true, it becomes impossible to select the tab for the second time or the third time.

The following is the operation capture.

Https://i.gyazo.com/190a4f02265d4795e8ff7038ea7cf4f5.mp4

Debugging while seeing the source code

Https://github.com/EndouMari/TabPageViewController/blob/master/Sources/TabView.swift#L258

If you omit the above if statement, it looks like it works normally.

Https://i.gyazo.com/107a8fdd661b02a414076e3a58350607.mp4

Since I am not chasing deeply, can you check whether there is no problem just by deleting this if statement?
I will send you a PR after this. Thank you.

**Comment by EndouMari** [comment]
issueありがとうございます！
PR確認してマージしました。

**Comment by isseium** [comment]
ありがとうございます！！
thanks!
