### ISSUE TITLE
Error: 'TabPageOption' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by kakubei** [EndouMari/TabPageViewController#7]
I get this error using code from the example project. 

Cocoapods latest installed version of TabPageViewController is 0.1.0.

Please advise.

**Comment by EndouMari** [comment]
I deployed TabPageViewController of  0.1.1.
Please pod install again.

**Comment by EndouMari** [comment]
I deployed 0.1.0.
Please, pod install again.
