### ISSUE TITLE
How i can set Position of menu?

### ISSUE THREAD

**Issue by amirch123** [EndouMari/TabPageViewController#76]
Hello
I want to move my menu to the middle of the scree.
plz help

**Comment by EndouMari** [comment]
Thanks issue.
What's menu?

**Comment by amirch123** [comment]
Thanks for answering
Actually I want to move menu to the middle of the scree, and put a button on top of it.
like picure
![simulator screen shot aug 16 2017 12 13 16 pm](https://user-images.githubusercontent.com/25988633/29352686-f052693e-827c-11e7-811d-406f2ff093a4.png)

**Comment by EndouMari** [comment]
1. move menu to the middle 
-> Sorry, it's not supported. 

2. put a button on top
-> Please adjust the viewController's contentInset
