### ISSUE TITLE
少ない数のタブメニューを画面いっぱいにしたい

### ISSUE THREAD

**Issue by TougeHiroyuki** [EndouMari/TabPageViewController#87]
例えばこのTabPageViewControllerにFirstとSecondの2つのViewControllerを入れたい場合、
2つだけの場合だとタブのFirstとSecondは左側に寄ってしまいますが、
これを各タブ均等な幅で、画面幅いっぱいに設定することはできますか？

**Comment by EndouMari** [comment]
タブのwidthを設定できるのでそれを設定するのが良いと思います。

**Comment by TougeHiroyuki** [comment]
TabPageOption.swiftにありました、ありがとうございます。
```
public var tabWidth: CGFloat?
```
このオプションを設定していなかったので、widthがintrinsicContentSizeに合わさっていました。
```
if let tabWidth = option.tabWidth , tabWidth > 0.0 {
    width = tabWidth
} else {
    width = itemLabel.intrinsicContentSize.width + option.tabMargin * 2
}
```

最高のライブラリをありがとうございます！
