### ISSUE TITLE
errors after pod installation (Xcode 9.3.1) 

### ISSUE THREAD

**Issue by 7ur7Le** [EndouMari/TabPageViewController#90]
<img width="1372" alt="screen shot 2018-05-25 at 4 42 13 pm" src="https://user-images.githubusercontent.com/26501778/40541728-9f05f716-603a-11e8-8d3e-1520dc83890d.png">

 
<img width="1387" alt="screen shot 2018-05-25 at 4 39 49 pm" src="https://user-images.githubusercontent.com/26501778/40541667-585c358c-603a-11e8-880c-c866e287c318.png">

**Comment by connorford2** [comment]
I have the same issue. Did you find a fix?

**Comment by tphduy** [comment]
Just a declaration error, replace `((Void) -> Void)?` by `(() -> ())?` in TabCollectionCell.swift
